apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-eks-ingress-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: "https://bitbucket.org/workspace-testing-eks/testing-eks-gitops-repo.git"
    targetRevision: main
    path: k8s-manifest/dev/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
